/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bo.TCPIP;
import bo.TP650;
import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.Timer;
import pst.MsgPST;
import pst.SenhaPST;
import to.DadosCarregTO;

/**
 *
 * @author anderson
 */
public class TelaImprimirSenhaGUI extends javax.swing.JFrame {

    private TelaInicialCPFGUI telaInicialCPFGUI;
    private boolean fechaTela;

    /**
     * Creates new form TelaImprimirSenhaGUI
     */
    public TelaImprimirSenhaGUI(TelaInicialCPFGUI telaInicialCPFGUI) {
        initComponents();
        fechaTela = false;

        this.telaInicialCPFGUI = telaInicialCPFGUI;
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonOK = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jButtonCanc = new javax.swing.JButton();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelMsg1 = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelMsg = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButtonOK.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().add(jButtonOK, gridBagConstraints);

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonFechar.setText("X");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButtonFechar, gridBagConstraints);

        jButtonCanc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCanc.setText("Cancelar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        getContentPane().add(jButtonCanc, gridBagConstraints);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("AUTOATENDIMENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelTitulo, gridBagConstraints);

        jLabelMsg1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMsg1.setText("Ok, registro efetuado com sucesso, retire sua senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        getContentPane().add(jLabelMsg1, gridBagConstraints);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelSenha.setText("00000ASC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 40, 0);
        getContentPane().add(jLabelSenha, gridBagConstraints);

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 34)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus.setText("Status: Pendende de liberação transportadora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 30, 0);
        getContentPane().add(jLabelStatus, gridBagConstraints);

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo2.setText("SISTEMA DE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        getContentPane().add(jLabelTitulo2, gridBagConstraints);

        jLabelMsg.setColumns(30);
        jLabelMsg.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabelMsg.setRows(4);
        jLabelMsg.setDisabledTextColor(new java.awt.Color(255, 0, 0));
        jLabelMsg.setEnabled(false);
        jLabelMsg.setPreferredSize(new java.awt.Dimension(800, 100));
        jScrollPane1.setViewportView(jLabelMsg);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 60;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:

        JLabel label = new JLabel("Digite a senha:");
        JPasswordField jpf = new JPasswordField();
        JOptionPane msg = new JOptionPane(new Object[]{label, jpf}, JOptionPane.OK_CANCEL_OPTION);
        JDialog dlg = msg.createDialog("Password");
        dlg.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                super.componentShown(e);
                final Timer t = new Timer(10000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        dlg.setVisible(false);
                    }
                });
                t.start();
            }
        });
        dlg.setVisible(true);

        String senha = new String(jpf.getPassword());
        SenhaPST senhaPST = new SenhaPST();

        if (senha.equals(senhaPST.retornaSenha())) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:

        try {
            fechaTela = true;
            this.telaInicialCPFGUI.limpaCPF();
            this.telaInicialCPFGUI.setVisible(true);
            this.setVisible(false);
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButtonOKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanc;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JTextArea jLabelMsg;
    private javax.swing.JLabel jLabelMsg1;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void exibir() {
        jLabelSenha.setText(this.telaInicialCPFGUI.getDadosCarregTO().getSenha());
        jLabelStatus.setText("STATUS: " + this.telaInicialCPFGUI.getDadosCarregTO().getDescrEtapa());
        MsgPST msgPST = new MsgPST();
        String tipo;
        if (this.telaInicialCPFGUI.getDadosCarregTO().getIdProdCarreg().equals("1")
                || this.telaInicialCPFGUI.getDadosCarregTO().getIdProdCarreg().equals("2")) {
            tipo = "1";
        } else {
            tipo = "2";
        }
        if (this.telaInicialCPFGUI.getDadosCarregTO().getIdEtapa().trim().equals("2")) {
            telaInicialCPFGUI.getDadosCarregTO().setConfirmaDados(0);
        }
        jLabelMsg.setText(msgPST.retornaMsg(tipo, this.telaInicialCPFGUI.getDadosCarregTO().getConfirmaDados()).replace(".", ".\n").toUpperCase());
            jLabelMsg.setLineWrap(true);
        
        imprimir();
        
    }

    public void fechaTela() {
        Timer t = new Timer(30000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                fechar();
            }
        });
        t.start();
    }

    public void fechar() {
        if (!fechaTela) {
            fechaTela = true;
            this.telaInicialCPFGUI.limpaCPF();
            this.telaInicialCPFGUI.setVisible(true);
            this.setVisible(false);
        }
    }

    public void setFechaTela(boolean fechaTela) {
        this.fechaTela = fechaTela;
    }

    private void imprimir() {
        
        System.out.println("USINA SANTA FE S.A.");
        System.out.println("TICKET DE CARREGAMENTO");
        System.out.println(this.telaInicialCPFGUI.getDadosCarregTO().getSenha());
        System.out.println("PLACAS: " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca1()
                        + " | " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca2()
                        + " | " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca3() + "");
        System.out.println(this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista());
        
//        try {
//            TCPIP s = new TCPIP();
//            TP650 tp = new TP650();
//            s.connect();
//            s.write(tp.textoNormal(""));
//            s.write(tp.textoNormal("USINA SANTA FE S.A."));
//            s.write("\n");
//            s.write("\n");
//            s.write(tp.textoNormal("TICKET DE CARREGAMENTO"));
//            s.write("\n");
//            s.write(tp.textoNegrito(this.telaInicialCPFGUI.getDadosCarregTO().getSenha()));
//            s.write("\n");
//            s.write("\n");
//            s.write(tp.textoNormal("PLACAS: " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca1()
//                                    + " | " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca2()
//                                    + " | " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca3() + ""));
//            s.write("\n");
//            if(!this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista().equals("0")){
//                s.write(tp.textoNormal(this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista()));
//            }
//            s.write("\n");
//            s.write("\n");
//            s.write(tp.qrcode(8, this.telaInicialCPFGUI.getDadosCarregTO().getSenha()));
//            s.write("\n");
//            s.write("\n");
//            s.write("\n");
//            s.write("\n");
//            s.write(tp.abreGaveta(0, 4));
//            s.write("\n\n\n\n");
//            s.write(tp.cortePapel());
//            s.close();
//        } catch (IOException ex) {
//            Logger.getLogger(TelaImprimirSenhaGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

}
