/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.Timer;
import pst.SenhaPST;

/**
 *
 * @author anderson
 */
public class TelaPlacaGUI extends javax.swing.JFrame {

    private TelaInicialCPFGUI telaInicialCPFGUI;
    private String textoPlaca;
    private int qtde;

    /**
     * Creates new form TelaPlacaGUI
     */
    public TelaPlacaGUI(TelaInicialCPFGUI telaInicialCPFGUI) {
        initComponents();
        this.telaInicialCPFGUI = telaInicialCPFGUI;
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelMsg = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jButtonCanc = new javax.swing.JButton();
        jLabelPlaca = new javax.swing.JLabel();
        jPanelPrincPlaca = new javax.swing.JPanel();
        jLabelTitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelMsg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMsg.setText("Registre sua placa.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        getContentPane().add(jLabelMsg, gridBagConstraints);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("AUTOATENDIMENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelTitulo, gridBagConstraints);

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonFechar.setText("X");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButtonFechar, gridBagConstraints);

        jButtonCanc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCanc.setText("CANCELAR");
        jButtonCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        getContentPane().add(jButtonCanc, gridBagConstraints);

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelPlaca.setText("___-____");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        getContentPane().add(jLabelPlaca, gridBagConstraints);

        jPanelPrincPlaca.setPreferredSize(new java.awt.Dimension(800, 450));

        javax.swing.GroupLayout jPanelPrincPlacaLayout = new javax.swing.GroupLayout(jPanelPrincPlaca);
        jPanelPrincPlaca.setLayout(jPanelPrincPlacaLayout);
        jPanelPrincPlacaLayout.setHorizontalGroup(
            jPanelPrincPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanelPrincPlacaLayout.setVerticalGroup(
            jPanelPrincPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 800;
        gridBagConstraints.ipady = 450;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        getContentPane().add(jPanelPrincPlaca, gridBagConstraints);

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo2.setText("SISTEMA DE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        getContentPane().add(jLabelTitulo2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:

        JLabel label = new JLabel("Digite a senha:");
        JPasswordField jpf = new JPasswordField();
        JOptionPane msg = new JOptionPane(new Object[]{label, jpf}, JOptionPane.OK_CANCEL_OPTION);
        JDialog dlg = msg.createDialog("Password");
        dlg.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                super.componentShown(e);
                final Timer t = new Timer(10000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        dlg.setVisible(false);
                    }
                });
                t.start();
            }
        });
        dlg.setVisible(true);

        String senha = new String(jpf.getPassword());
        SenhaPST senhaPST = new SenhaPST();

        if (senha.equals(senhaPST.retornaSenha())) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancActionPerformed
        // TODO add your handling code here:

        this.telaInicialCPFGUI.limpaCPF();
        this.telaInicialCPFGUI.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonCancActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaPlacaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaPlacaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaPlacaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaPlacaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaPlacaGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanc;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JPanel jPanelPrincPlaca;
    // End of variables declaration//GEN-END:variables

    public JPanel getjPanelPrincPlaca() {
        return jPanelPrincPlaca;
    }

    public void setjPanelPrincPlaca(JPanel jPanelPrincPlaca) {
        this.jPanelPrincPlaca = jPanelPrincPlaca;
    }

    public void preencherLabelPlaca(String texto) {

        switch (qtde) {
            case 0:
                qtde++;
                textoPlaca = textoPlaca + texto;
                jLabelPlaca.setText(textoPlaca + "__-____");
                break;
            case 1:
                qtde++;
                textoPlaca = textoPlaca + texto;
                jLabelPlaca.setText(textoPlaca + "_-____");
                break;
            case 2:
                qtde++;
                textoPlaca = textoPlaca + texto;
                jLabelPlaca.setText(textoPlaca + "-____");
                JPanelTecladoNum jPanelTecladoNum = new JPanelTecladoNum(this);
                jPanelTecladoNum.setSize(820, 440);
                jPanelTecladoNum.setLocation(0, 0);

                jPanelPrincPlaca.removeAll();
                jPanelPrincPlaca.add(jPanelTecladoNum, BorderLayout.CENTER);
                jPanelPrincPlaca.revalidate();
                jPanelPrincPlaca.repaint();
                break;
            case 3:
                qtde++;
                textoPlaca = textoPlaca + '-' + texto;
                jLabelPlaca.setText(textoPlaca + "___");
                break;
            case 4:
                qtde++;
                textoPlaca = textoPlaca + texto;
                jLabelPlaca.setText(textoPlaca + "__");
                break;
            case 5:
                qtde++;
                textoPlaca = textoPlaca + texto;
                jLabelPlaca.setText(textoPlaca + "_");
                break;
            case 6:
                qtde++;
                textoPlaca = textoPlaca + texto;
                jLabelPlaca.setText(textoPlaca);
                break;
            default:
                break;
        }
    }

    public void apagarLabelPlaca() {
        switch (qtde) {
            case 1:
                qtde--;
                textoPlaca = textoPlaca.substring(0, textoPlaca.length() - 1);
                jLabelPlaca.setText(textoPlaca + "___-____");
                break;
            case 2:
                qtde--;
                textoPlaca = textoPlaca.substring(0, textoPlaca.length() - 1);
                jLabelPlaca.setText(textoPlaca + "__-____");
                break;
            case 3:
                qtde--;
                textoPlaca = textoPlaca.substring(0, textoPlaca.length() - 1);
                jLabelPlaca.setText(textoPlaca + "_-____");
                break;
            case 4:
                qtde--;
                textoPlaca = textoPlaca.substring(0, textoPlaca.length() - 2);
                jLabelPlaca.setText(textoPlaca + "-____");
                break;
            case 5:
                qtde--;
                textoPlaca = textoPlaca.substring(0, textoPlaca.length() - 1);
                jLabelPlaca.setText(textoPlaca + "___");
                break;
            case 6:
                qtde--;
                textoPlaca = textoPlaca.substring(0, textoPlaca.length() - 1);
                jLabelPlaca.setText(textoPlaca + "__");
                break;
            case 7:
                qtde--;
                textoPlaca = textoPlaca.substring(0, textoPlaca.length() - 1);
                jLabelPlaca.setText(textoPlaca + "_");
                break;
            default:
                break;
        }
    }

    public TelaInicialCPFGUI getTelaInicialCPFGUI() {
        return telaInicialCPFGUI;
    }

    public void setTelaInicialCPFGUI(TelaInicialCPFGUI telaInicialCPFGUI) {
        this.telaInicialCPFGUI = telaInicialCPFGUI;
    }

    public JLabel getjLabelPlaca() {
        return jLabelPlaca;
    }

    public void setTextoPlaca(String textoPlaca) {
        this.textoPlaca = textoPlaca;
    }

    public String getTextoPlaca() {
        return textoPlaca;
    }
    
    public void setQtde(int qtde) {
        this.qtde = qtde;
    }

    public int getQtde() {
        return qtde;
    }

    public void chamaTecladoLetra() {
        JPanelTecladoLetra jPanelTecladoLetra = new JPanelTecladoLetra(this);
        jPanelTecladoLetra.setSize(820, 285);
        jPanelTecladoLetra.setLocation(0, 0);

        jPanelPrincPlaca.removeAll();
        jPanelPrincPlaca.add(jPanelTecladoLetra, BorderLayout.CENTER);
        jPanelPrincPlaca.revalidate();
        jPanelPrincPlaca.repaint();
    }

    public void limpaPlaca() {
        jLabelPlaca.setText("___-____");
        textoPlaca = "";
        qtde = 0;
        this.telaInicialCPFGUI.getDadosCarregTO().setPlaca1("");
        this.telaInicialCPFGUI.getDadosCarregTO().setPlaca2(null);
        this.telaInicialCPFGUI.getDadosCarregTO().setPlaca3(null);
    }

}
