/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import bo.TCPIP;
import bo.TP650;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.io.IOException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.Timer;
import pst.ReimpressaoPST;
import pst.SenhaPST;

/**
 *
 * @author anderson
 */
public class TelaCamCPreOrdemGUI extends javax.swing.JFrame {

    private TelaInicialCPFGUI telaInicialCPFGUI;

    /**
     * Creates new form TelaCamCPreOrdem
     */
    public TelaCamCPreOrdemGUI(TelaInicialCPFGUI telaInicialCPFGUI) {
        initComponents();
        this.telaInicialCPFGUI = telaInicialCPFGUI;
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTitulo = new javax.swing.JLabel();
        jButtonCanc = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jLabelTitulo2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelMsg = new javax.swing.JTextArea();
        jButtonReimpressao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("AUTOATENDIMENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelTitulo, gridBagConstraints);

        jButtonCanc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCanc.setText("CANCELAR");
        jButtonCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        getContentPane().add(jButtonCanc, gridBagConstraints);

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonFechar.setText("X");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButtonFechar, gridBagConstraints);

        jButtonOK.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 10, 150);
        getContentPane().add(jButtonOK, gridBagConstraints);

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo2.setText("SISTEMA DE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        getContentPane().add(jLabelTitulo2, gridBagConstraints);

        jLabelMsg.setColumns(30);
        jLabelMsg.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabelMsg.setRows(10);
        jLabelMsg.setDisabledTextColor(new java.awt.Color(255, 51, 51));
        jLabelMsg.setEnabled(false);
        jLabelMsg.setPreferredSize(new java.awt.Dimension(800, 350));
        jScrollPane1.setViewportView(jLabelMsg);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jButtonReimpressao.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonReimpressao.setText("REIMPRESSÃO");
        jButtonReimpressao.setActionCommand("jButtonReimpressao");
        jButtonReimpressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReimpressaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(20, 150, 10, 10);
        getContentPane().add(jButtonReimpressao, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancActionPerformed
        // TODO add your handling code here:

        this.telaInicialCPFGUI.limpaCPF();
        this.telaInicialCPFGUI.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonCancActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:

        this.telaInicialCPFGUI.limpaCPF();
        this.telaInicialCPFGUI.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:

        JLabel label = new JLabel("Digite a senha:");
        JPasswordField jpf = new JPasswordField();
        JOptionPane msg = new JOptionPane(new Object[]{label, jpf}, JOptionPane.OK_CANCEL_OPTION);
        JDialog dlg = msg.createDialog("Password");
        dlg.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                super.componentShown(e);
                final Timer t = new Timer(10000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        dlg.setVisible(false);
                    }
                });
                t.start();
            }
        });
        dlg.setVisible(true);

        String senha = new String(jpf.getPassword());
        SenhaPST senhaPST = new SenhaPST();

        if (senha.equals(senhaPST.retornaSenha())) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonReimpressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReimpressaoActionPerformed
        // TODO add your handling code here:
        
        imprimir();
        
    }//GEN-LAST:event_jButtonReimpressaoActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaCamCPreOrdemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaCamCPreOrdemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaCamCPreOrdemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaCamCPreOrdemGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaCamCPreOrdemGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanc;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonReimpressao;
    private javax.swing.JTextArea jLabelMsg;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void preencher() {
        jLabelMsg.setText(this.telaInicialCPFGUI.getDadosCarregTO().getMsgErro().replace(".", ".\n").toUpperCase());
        jLabelMsg.setLineWrap(true);
    }
    
    private void imprimir() {

        if(!this.telaInicialCPFGUI.getDadosCarregTO().getIdPreOrdCarreg().equals("0")){

            ReimpressaoPST reimpressaoPST = new ReimpressaoPST();
            this.telaInicialCPFGUI.setDadosCarregTO(reimpressaoPST.retReimpressao(this.telaInicialCPFGUI.getDadosCarregTO()));

//            System.out.println("USINA SANTA FE S.A.");
//            System.out.println("TICKET DE CARREGAMENTO");
//            System.out.println(this.telaInicialCPFGUI.getDadosCarregTO().getSenha());
//            System.out.println("PLACAS: " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca1()
//                            + " | " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca2()
//                            + " | " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca3() + "");
//            System.out.println(this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista());

            if(this.telaInicialCPFGUI.getDadosCarregTO().getMsg().equals("")){

                reimpressaoPST.addReimpressao(this.telaInicialCPFGUI.getDadosCarregTO());

                try {
                    TCPIP s = new TCPIP();
                    TP650 tp = new TP650();
                    s.connect();
                    s.write(tp.textoNormal(""));
                    s.write(tp.textoNormal("USINA SANTA FE S.A."));
                    s.write("\n");
                    s.write("\n");
                    s.write(tp.textoNormal("TICKET DE CARREGAMENTO"));
                    s.write("\n");
                    s.write(tp.textoNegrito(this.telaInicialCPFGUI.getDadosCarregTO().getSenha()));
                    s.write("\n");
                    s.write("\n");
                    s.write(tp.textoNormal("PLACAS: " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca1()
                                            + " | " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca2()
                                            + " | " + this.telaInicialCPFGUI.getDadosCarregTO().getPlaca3() + ""));
                    s.write("\n");
                    if(!this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista().equals("0")){
                        s.write(tp.textoNormal(this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista()));
                    }
                    s.write("\n");
                    s.write("\n");
                    s.write(tp.qrcode(8, this.telaInicialCPFGUI.getDadosCarregTO().getSenha()));
                    s.write("\n");
                    s.write("\n");
                    s.write("\n");
                    s.write("\n");
                    s.write(tp.abreGaveta(0, 4));
                    s.write("\n\n\n\n");
                    s.write(tp.cortePapel());
                    s.close();

                } catch (IOException ex) {
                    Logger.getLogger(TelaImprimirSenhaGUI.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
            else{
                
                this.telaInicialCPFGUI.getjDialogDefault().setTxtMsg(this.telaInicialCPFGUI.getDadosCarregTO().getMsg());
                Timer timer = new Timer(4000, new ActionListener() {
                    public void actionPerformed(ActionEvent e) {
                        telaInicialCPFGUI.getjDialogDefault().setVisible(false);
                    }
                });
                timer.setRepeats(false);
                timer.start();
                this.telaInicialCPFGUI.getjDialogDefault().setVisible(true);
            
            }
            
        }
        else{
            
            this.telaInicialCPFGUI.getjDialogDefault().setTxtMsg("NÃO CONTÉM NENHUMA PRÉ ORDEM DE CARREGAMENTO PARA ESSE CPF! POR FAVOR, ENTRE EM CONTATO COM O NÚCLEO FISCAL.");
            Timer timer = new Timer(4000, new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    telaInicialCPFGUI.getjDialogDefault().setVisible(false);
                }
            });
            timer.setRepeats(false);
            timer.start();
            this.telaInicialCPFGUI.getjDialogDefault().setVisible(true);
            
        }
        
    }

}
