/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.Timer;
import pst.SenhaPST;

/**
 *
 * @author anderson
 */
public class TelaClassifProdCarregGUI extends javax.swing.JFrame {

    private TelaInicialCPFGUI telaInicialCPFGUI;

    /**
     * Creates new form TelaClassifProdCarregGUI
     */
    public TelaClassifProdCarregGUI(TelaInicialCPFGUI telaInicialCPFGUI) {
        initComponents();
        this.telaInicialCPFGUI = telaInicialCPFGUI;

        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelClassifProd = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jButtonCanc = new javax.swing.JButton();
        jButtonClassif1 = new javax.swing.JButton();
        jButtonClassif2 = new javax.swing.JButton();
        jLabelTitulo2 = new javax.swing.JLabel();
        jButtonClassif3 = new javax.swing.JButton();
        jButtonClassif4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelClassifProd.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        jLabelClassifProd.setText("Qual a classificação do Produto?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 30, 0);
        getContentPane().add(jLabelClassifProd, gridBagConstraints);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("AUTOATENDIMENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelTitulo, gridBagConstraints);

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonFechar.setText("X");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButtonFechar, gridBagConstraints);

        jButtonCanc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCanc.setText("CANCELAR");
        jButtonCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        getContentPane().add(jButtonCanc, gridBagConstraints);

        jButtonClassif1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClassif1.setText("AÇÚCAR");
        jButtonClassif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassif1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 80;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        getContentPane().add(jButtonClassif1, gridBagConstraints);

        jButtonClassif2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClassif2.setText("ETANOL");
        jButtonClassif2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassif2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 80;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        getContentPane().add(jButtonClassif2, gridBagConstraints);

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo2.setText("SISTEMA DE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        getContentPane().add(jLabelTitulo2, gridBagConstraints);

        jButtonClassif3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClassif3.setText("AÇÚCAR");
        jButtonClassif3.setActionCommand("jButtonClassif3");
        jButtonClassif3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassif3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 80;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        getContentPane().add(jButtonClassif3, gridBagConstraints);

        jButtonClassif4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButtonClassif4.setText("ETANOL");
        jButtonClassif4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassif4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 80;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        getContentPane().add(jButtonClassif4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:

        JLabel label = new JLabel("Digite a senha:");
        JPasswordField jpf = new JPasswordField();
        JOptionPane msg = new JOptionPane(new Object[]{label, jpf}, JOptionPane.OK_CANCEL_OPTION);
        JDialog dlg = msg.createDialog("Password");
        dlg.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                super.componentShown(e);
                final Timer t = new Timer(10000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        dlg.setVisible(false);
                    }
                });
                t.start();
            }
        });
        dlg.setVisible(true);

        String senha = new String(jpf.getPassword());
        SenhaPST senhaPST = new SenhaPST();

        if (senha.equals(senhaPST.retornaSenha())) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancActionPerformed
        // TODO add your handling code here:

        this.telaInicialCPFGUI.limpaCPF();
        this.telaInicialCPFGUI.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonCancActionPerformed

    private void jButtonClassif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassif1ActionPerformed
        // TODO add your handling code here:

        if (this.telaInicialCPFGUI.getDadosCarregTO().getIdProdCarreg().equals("acucar")) {
            this.telaInicialCPFGUI.getDadosCarregTO().setIdProdCarreg("2");
        } else {
            this.telaInicialCPFGUI.getDadosCarregTO().setIdProdCarreg("3");
        }

        if (this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista().equals("0")) {
            this.telaInicialCPFGUI.getTelaPlacaGUI().limpaPlaca();
            this.telaInicialCPFGUI.getTelaPlacaGUI().chamaTecladoLetra();
            this.telaInicialCPFGUI.getTelaPlacaGUI().setVisible(true);
            this.setVisible(false);
        } else {
            this.telaInicialCPFGUI.getTelaTranspUltCarregGUI().carreg();
            this.telaInicialCPFGUI.getTelaTranspUltCarregGUI().setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_jButtonClassif1ActionPerformed

    private void jButtonClassif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassif2ActionPerformed
        // TODO add your handling code here:

        if (this.telaInicialCPFGUI.getDadosCarregTO().getIdProdCarreg().equals("acucar")) {
            this.telaInicialCPFGUI.getDadosCarregTO().setIdProdCarreg("1");
        } else {
            this.telaInicialCPFGUI.getDadosCarregTO().setIdProdCarreg("4");
        }

        if (this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista().equals("0")) {
            this.telaInicialCPFGUI.getTelaPlacaGUI().limpaPlaca();
            this.telaInicialCPFGUI.getTelaPlacaGUI().chamaTecladoLetra();
            this.telaInicialCPFGUI.getTelaPlacaGUI().setVisible(true);
            this.setVisible(false);
        } else {
            this.telaInicialCPFGUI.getTelaTranspUltCarregGUI().carreg();
            this.telaInicialCPFGUI.getTelaTranspUltCarregGUI().setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_jButtonClassif2ActionPerformed

    private void jButtonClassif3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassif3ActionPerformed
        // TODO add your handling code here:
        
        this.telaInicialCPFGUI.getDadosCarregTO().setIdProdCarreg("7");

        if (this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista().equals("0")) {
            this.telaInicialCPFGUI.getTelaPlacaGUI().limpaPlaca();
            this.telaInicialCPFGUI.getTelaPlacaGUI().chamaTecladoLetra();
            this.telaInicialCPFGUI.getTelaPlacaGUI().setVisible(true);
            this.setVisible(false);
        } else {
            this.telaInicialCPFGUI.getTelaTranspUltCarregGUI().carreg();
            this.telaInicialCPFGUI.getTelaTranspUltCarregGUI().setVisible(true);
            this.setVisible(false);
        } 
        
    }//GEN-LAST:event_jButtonClassif3ActionPerformed

    private void jButtonClassif4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassif4ActionPerformed
        // TODO add your handling code here:
        
        this.telaInicialCPFGUI.getDadosCarregTO().setIdProdCarreg("8");

        if (this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista().equals("0")) {
            this.telaInicialCPFGUI.getTelaPlacaGUI().limpaPlaca();
            this.telaInicialCPFGUI.getTelaPlacaGUI().chamaTecladoLetra();
            this.telaInicialCPFGUI.getTelaPlacaGUI().setVisible(true);
            this.setVisible(false);
        } else {
            this.telaInicialCPFGUI.getTelaTranspUltCarregGUI().carreg();
            this.telaInicialCPFGUI.getTelaTranspUltCarregGUI().setVisible(true);
            this.setVisible(false);
        } 
        
        
    }//GEN-LAST:event_jButtonClassif4ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaClassifProdCarregGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaClassifProdCarregGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaClassifProdCarregGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaClassifProdCarregGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaClassifProdCarregGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanc;
    private javax.swing.JButton jButtonClassif1;
    private javax.swing.JButton jButtonClassif2;
    private javax.swing.JButton jButtonClassif3;
    private javax.swing.JButton jButtonClassif4;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JLabel jLabelClassifProd;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    // End of variables declaration//GEN-END:variables

    public void exibir() {
        if (this.telaInicialCPFGUI.getDadosCarregTO().getIdProdCarreg().equals("acucar")) {
            jButtonClassif1.setText("AÇÚCAR ENSACADO");
            jButtonClassif2.setText("AÇÚCAR BIG BAG");
            jButtonClassif3.enable(true);
            jButtonClassif3.setText("AÇÚCAR GRANEL");
            jButtonClassif4.enable(true);
            jButtonClassif4.setText("AÇUCAR CONTAINER");
        } else {
            jButtonClassif1.setText("ETANOL HIDRATADO");
            jButtonClassif2.setText("ETANOL ANIDRO");
            jButtonClassif3.enable(false);
            jButtonClassif4.enable(false);
        }
    }

}
