/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.Timer;
import pst.SenhaPST;

/**
 *
 * @author anderson
 */
public class TelaWhatsappGUI extends javax.swing.JFrame {

    private TelaInicialCPFGUI telaInicialCPFGUI;
    private String textoCelular;
    private int qtde = 0;

    /**
     * Creates new form TelaWhatsappGUI
     */
    public TelaWhatsappGUI(TelaInicialCPFGUI telaInicialCPFGUI) {
        initComponents();
        this.telaInicialCPFGUI = telaInicialCPFGUI;
        textoCelular = "";
        setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelTitulo = new javax.swing.JLabel();
        jButtonFechar = new javax.swing.JButton();
        jButtonCanc = new javax.swing.JButton();
        jLabelCelular = new javax.swing.JLabel();
        jLabelMsg = new javax.swing.JLabel();
        jButtonCorrige = new javax.swing.JButton();
        jButtonNum2 = new javax.swing.JButton();
        jButtonNum3 = new javax.swing.JButton();
        jButtonNum1 = new javax.swing.JButton();
        jButtonNum4 = new javax.swing.JButton();
        jButtonNum7 = new javax.swing.JButton();
        jButtonNum5 = new javax.swing.JButton();
        jButtonNum8 = new javax.swing.JButton();
        jButtonNum0 = new javax.swing.JButton();
        jButtonNum6 = new javax.swing.JButton();
        jButtonNum9 = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jLabelTitulo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1280, 720));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        layout.rowHeights = new int[] {0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0, 5, 0};
        getContentPane().setLayout(layout);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("AUTOATENDIMENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabelTitulo, gridBagConstraints);

        jButtonFechar.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonFechar.setText("X");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 14;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 10);
        getContentPane().add(jButtonFechar, gridBagConstraints);

        jButtonCanc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCanc.setText("CANCELAR");
        jButtonCanc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 40;
        gridBagConstraints.ipady = 65;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 5, 0);
        getContentPane().add(jButtonCanc, gridBagConstraints);

        jLabelCelular.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabelCelular.setText("(__) _____-____");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        getContentPane().add(jLabelCelular, gridBagConstraints);

        jLabelMsg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMsg.setText("Informe seu whatsapp por favor.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        getContentPane().add(jLabelMsg, gridBagConstraints);

        jButtonCorrige.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonCorrige.setText("CORRIGE");
        jButtonCorrige.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCorrigeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 6;
        gridBagConstraints.ipady = 80;
        getContentPane().add(jButtonCorrige, gridBagConstraints);

        jButtonNum2.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum2.setText("2");
        jButtonNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum2, gridBagConstraints);

        jButtonNum3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum3.setText("3");
        jButtonNum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum3, gridBagConstraints);

        jButtonNum1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum1.setText("1");
        jButtonNum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum1, gridBagConstraints);

        jButtonNum4.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum4.setText("4");
        jButtonNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum4, gridBagConstraints);

        jButtonNum7.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum7.setText("7");
        jButtonNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum7, gridBagConstraints);

        jButtonNum5.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum5.setText("5");
        jButtonNum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum5, gridBagConstraints);

        jButtonNum8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum8.setText("8");
        jButtonNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum8, gridBagConstraints);

        jButtonNum0.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum0.setText("0");
        jButtonNum0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum0, gridBagConstraints);

        jButtonNum6.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum6.setText("6");
        jButtonNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum6, gridBagConstraints);

        jButtonNum9.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jButtonNum9.setText("9");
        jButtonNum9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNum9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.ipadx = 42;
        gridBagConstraints.ipady = 42;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 2, 5);
        getContentPane().add(jButtonNum9, gridBagConstraints);

        jButtonOK.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 55;
        getContentPane().add(jButtonOK, gridBagConstraints);

        jLabelTitulo2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo2.setText("SISTEMA DE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(40, 0, 0, 0);
        getContentPane().add(jLabelTitulo2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancActionPerformed
        // TODO add your handling code here:

        this.telaInicialCPFGUI.limpaCPF();
        this.telaInicialCPFGUI.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jButtonCancActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        // TODO add your handling code here:

        JLabel label = new JLabel("Digite a senha:");
        JPasswordField jpf = new JPasswordField();
        JOptionPane msg = new JOptionPane(new Object[]{label, jpf}, JOptionPane.OK_CANCEL_OPTION);
        JDialog dlg = msg.createDialog("Password");
        dlg.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                super.componentShown(e);
                final Timer t = new Timer(10000, new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        dlg.setVisible(false);
                    }
                });
                t.start();
            }
        });
        dlg.setVisible(true);

        String senha = new String(jpf.getPassword());
        SenhaPST senhaPST = new SenhaPST();

        if (senha.equals(senhaPST.retornaSenha())) {
            System.exit(0);
        }

    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonNum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum1ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("1");

    }//GEN-LAST:event_jButtonNum1ActionPerformed

    private void jButtonNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum2ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("2");

    }//GEN-LAST:event_jButtonNum2ActionPerformed

    private void jButtonNum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum3ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("3");

    }//GEN-LAST:event_jButtonNum3ActionPerformed

    private void jButtonNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum4ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("4");

    }//GEN-LAST:event_jButtonNum4ActionPerformed

    private void jButtonNum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum5ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("5");

    }//GEN-LAST:event_jButtonNum5ActionPerformed

    private void jButtonNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum6ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("6");

    }//GEN-LAST:event_jButtonNum6ActionPerformed

    private void jButtonNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum7ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("7");

    }//GEN-LAST:event_jButtonNum7ActionPerformed

    private void jButtonNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum8ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("8");

    }//GEN-LAST:event_jButtonNum8ActionPerformed

    private void jButtonNum9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum9ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("9");

    }//GEN-LAST:event_jButtonNum9ActionPerformed

    private void jButtonNum0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNum0ActionPerformed
        // TODO add your handling code here:

        preencherLabelCelular("0");

    }//GEN-LAST:event_jButtonNum0ActionPerformed

    private void jButtonCorrigeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCorrigeActionPerformed
        // TODO add your handling code here:

        apagarLabelCelular();

    }//GEN-LAST:event_jButtonCorrigeActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        // TODO add your handling code here:

        if (qtde == 11) {

            telaInicialCPFGUI.getDadosCarregTO().setCelular(textoCelular);
            if (this.telaInicialCPFGUI.getDadosCarregTO().getNomeMotorista().equals("0")) {
                telaInicialCPFGUI.getTelaProdutoCarregGUI().setVisible(true);
            } else {
                telaInicialCPFGUI.getTelaProdutoUltCarregGUI().carreg();
                telaInicialCPFGUI.getTelaProdutoUltCarregGUI().setVisible(true);
            }
            this.setVisible(false);

        } else {

            telaInicialCPFGUI.getjDialogDefault().setTxtMsg("Por Favor, termine de digitar o Whatsapp.");
            Timer timer = new Timer(4000, new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    telaInicialCPFGUI.getjDialogDefault().setVisible(false);
                }
            });
            timer.setRepeats(false);
            timer.start();
            telaInicialCPFGUI.getjDialogDefault().setVisible(true);
            
        }

    }//GEN-LAST:event_jButtonOKActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(TelaWhatsappGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(TelaWhatsappGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(TelaWhatsappGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(TelaWhatsappGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new TelaWhatsappGUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCanc;
    private javax.swing.JButton jButtonCorrige;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonNum0;
    private javax.swing.JButton jButtonNum1;
    private javax.swing.JButton jButtonNum2;
    private javax.swing.JButton jButtonNum3;
    private javax.swing.JButton jButtonNum4;
    private javax.swing.JButton jButtonNum5;
    private javax.swing.JButton jButtonNum6;
    private javax.swing.JButton jButtonNum7;
    private javax.swing.JButton jButtonNum8;
    private javax.swing.JButton jButtonNum9;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelCelular;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    // End of variables declaration//GEN-END:variables

    public void preencherLabelCelular(String texto) {
        switch (qtde) {
            case 0:
                qtde++;
                textoCelular = textoCelular + "(" + texto;
                jLabelCelular.setText(textoCelular + "_) _____-____");
                break;
            case 1:
                qtde++;
                textoCelular = textoCelular + texto;
                jLabelCelular.setText(textoCelular + ") _____-____");
                break;
            case 2:
                qtde++;
                textoCelular = textoCelular + ") " + texto;
                jLabelCelular.setText(textoCelular + "____-____");
                break;
            case 3:
                qtde++;
                textoCelular = textoCelular + texto;
                jLabelCelular.setText(textoCelular + "___-____");
                break;
            case 4:
                qtde++;
                textoCelular = textoCelular + texto;
                jLabelCelular.setText(textoCelular + "__-____");
                break;
            case 5:
                qtde++;
                textoCelular = textoCelular + texto;
                jLabelCelular.setText(textoCelular + "_-____");
                break;
            case 6:
                qtde++;
                textoCelular = textoCelular + texto;
                jLabelCelular.setText(textoCelular + "-____");
                break;
            case 7:
                qtde++;
                textoCelular = textoCelular + '-' + texto;
                jLabelCelular.setText(textoCelular + "___");
                break;
            case 8:
                qtde++;
                textoCelular = textoCelular + texto;
                jLabelCelular.setText(textoCelular + "__");
                break;
            case 9:
                qtde++;
                textoCelular = textoCelular + texto;
                jLabelCelular.setText(textoCelular + "_");
                break;
            case 10:
                qtde++;
                textoCelular = textoCelular + texto;
                jLabelCelular.setText(textoCelular);
                break;
            default:
                break;
        }
    }

    public void apagarLabelCelular() {
        switch (qtde) {
            case 1:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 2);
                jLabelCelular.setText(textoCelular + "(__) _____-____");
                break;
            case 2:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 1);
                jLabelCelular.setText(textoCelular + "_) _____-____");
                break;
            case 3:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 3);
                jLabelCelular.setText(textoCelular + ") _____-____");
                break;
            case 4:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 1);
                jLabelCelular.setText(textoCelular + "____-____");
                break;
            case 5:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 1);
                jLabelCelular.setText(textoCelular + "___-____");
                break;
            case 6:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 1);
                jLabelCelular.setText(textoCelular + "__-____");
                break;
            case 7:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 1);
                jLabelCelular.setText(textoCelular + "_-____");
                break;
            case 8:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 2);
                jLabelCelular.setText(textoCelular + "-____");
                break;
            case 9:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 1);
                jLabelCelular.setText(textoCelular + "___");
                break;
            case 10:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 1);
                jLabelCelular.setText(textoCelular + "__");
                break;
            case 11:
                qtde--;
                textoCelular = textoCelular.substring(0, textoCelular.length() - 1);
                jLabelCelular.setText(textoCelular + "_");
                break;
            default:
                break;
        }
    }

    public void limpaCelular() {
        jLabelCelular.setText("(__) _____-____");
        qtde = 0;
        textoCelular = "";
        this.telaInicialCPFGUI.getDadosCarregTO().setCelular("");
    }

}
