/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author anderson
 */
public class TelaClassifProdCarregJPanel extends javax.swing.JPanel {

    private final Image image;
    private final BaseJFrame baseJFrame;

    /**
     * Creates new form TelaClassifProdCarregJPanel
     */
    public TelaClassifProdCarregJPanel(BaseJFrame baseJFrame) {
        this.baseJFrame = baseJFrame;
        initComponents();
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/util/layout_totem.jpg"));
        this.image = imageIcon.getImage();
        exibir();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonCancelar = new javax.swing.JButton();
        jButtonRetornar = new javax.swing.JButton();
        jLabelClassifProd = new javax.swing.JLabel();
        jButtonClassif1 = new javax.swing.JButton();
        jButtonClassif2 = new javax.swing.JButton();
        jButtonClassif3 = new javax.swing.JButton();
        jButtonClassif4 = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 70;
        add(jButtonCancelar, gridBagConstraints);

        jButtonRetornar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRetornar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRetornar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonRetornar.setText("RETORNAR");
        jButtonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 70;
        add(jButtonRetornar, gridBagConstraints);

        jLabelClassifProd.setBackground(new java.awt.Color(255, 255, 255));
        jLabelClassifProd.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelClassifProd.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClassifProd.setText("Qual a classificação do Produto?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(120, 0, 120, 0);
        add(jLabelClassifProd, gridBagConstraints);

        jButtonClassif1.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClassif1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonClassif1.setForeground(new java.awt.Color(28, 88, 199));
        jButtonClassif1.setText("AÇÚCAR");
        jButtonClassif1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassif1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 10, 10);
        add(jButtonClassif1, gridBagConstraints);

        jButtonClassif2.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClassif2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonClassif2.setForeground(new java.awt.Color(28, 88, 199));
        jButtonClassif2.setText("ETANOL");
        jButtonClassif2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassif2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 10, 30);
        add(jButtonClassif2, gridBagConstraints);

        jButtonClassif3.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClassif3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonClassif3.setForeground(new java.awt.Color(28, 88, 199));
        jButtonClassif3.setText("AÇÚCAR");
        jButtonClassif3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassif3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.insets = new java.awt.Insets(10, 30, 0, 10);
        add(jButtonClassif3, gridBagConstraints);

        jButtonClassif4.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClassif4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonClassif4.setForeground(new java.awt.Color(28, 88, 199));
        jButtonClassif4.setText("ETANOL");
        jButtonClassif4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClassif4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 70;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 30);
        add(jButtonClassif4, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        this.baseJFrame.mudarTela("TelaCPFJPanel");

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonClassif1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassif1ActionPerformed

        this.baseJFrame.getAutomacaoCTR().classif1();
        mudarTela();

    }//GEN-LAST:event_jButtonClassif1ActionPerformed

    private void jButtonClassif2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassif2ActionPerformed

        this.baseJFrame.getAutomacaoCTR().classif2();
        mudarTela();

    }//GEN-LAST:event_jButtonClassif2ActionPerformed

    private void jButtonClassif3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassif3ActionPerformed

        this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().setIdProdCarreg("7");
        mudarTela();

    }//GEN-LAST:event_jButtonClassif3ActionPerformed

    private void jButtonClassif4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClassif4ActionPerformed

        this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().setIdProdCarreg("8");
        mudarTela();

    }//GEN-LAST:event_jButtonClassif4ActionPerformed

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed

        this.baseJFrame.retornarTela();

    }//GEN-LAST:event_jButtonRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonClassif1;
    private javax.swing.JButton jButtonClassif2;
    private javax.swing.JButton jButtonClassif3;
    private javax.swing.JButton jButtonClassif4;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JLabel jLabelClassifProd;
    // End of variables declaration//GEN-END:variables

    private void exibir() {
        if (this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getIdProdCarreg().equals("acucar")) {
            jButtonClassif1.setText("AÇÚCAR ENSACADO");
            jButtonClassif2.setText("AÇÚCAR BIG BAG");
            jButtonClassif3.enable(true);
            jButtonClassif3.setText("AÇÚCAR GRANEL");
            jButtonClassif4.enable(true);
            jButtonClassif4.setText("AÇUCAR CONTAINER");
        } else {
            jButtonClassif1.setText("ETANOL HIDRATADO");
            jButtonClassif2.setText("ETANOL ANIDRO");
            jButtonClassif3.enable(false);
            jButtonClassif4.enable(false);
        }
    }

    private void mudarTela() {
        if (this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getNomeMotorista().equals("0")) {
            this.baseJFrame.mudarTela("TelaPlacaJPanel");
        } else {
            this.baseJFrame.mudarTela("TelaTranspUltCarregJPanel");
        }
    }

    @Override
    public Dimension getPreferredSize() {
        Dimension superSize = super.getPreferredSize();
        if (isPreferredSizeSet() || image == null) {
            return superSize;
        }
        int prefW = Math.max(image.getWidth(null), superSize.width);
        int prefH = Math.max(image.getHeight(null), superSize.height);
        return new Dimension(prefW, prefH);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, null);
        }
    }

}
