/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import util.Const;

/**
 *
 * @author anderson
 */
public class TelaUltClienteCarregJPanel extends javax.swing.JPanel {

    private final Image image;
    private final BaseJFrame baseJFrame;

    /**
     * Creates new form TelaClienteUltCarregJPanel
     *
     * @param baseJFrame
     */
    public TelaUltClienteCarregJPanel(BaseJFrame baseJFrame) {
        this.baseJFrame = baseJFrame;
        initComponents();
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/util/layout_totem.jpg"));
        this.image = imageIcon.getImage();
        carreg();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonCancelar = new javax.swing.JButton();
        jButtonRetornar = new javax.swing.JButton();
        jLabelPerg = new javax.swing.JLabel();
        jLabelCliente = new javax.swing.JLabel();
        jLabelRuaNumero = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidadeUF = new javax.swing.JLabel();
        jButtonNão = new javax.swing.JButton();
        jButtonSim = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        add(jButtonCancelar, gridBagConstraints);

        jButtonRetornar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRetornar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRetornar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonRetornar.setText("RETORNAR");
        jButtonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        add(jButtonRetornar, gridBagConstraints);

        jLabelPerg.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabelPerg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPerg.setText("O Cliente do carregamento é?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(100, 0, 20, 0);
        add(jLabelPerg, gridBagConstraints);

        jLabelCliente.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCliente.setText("Cliente");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(jLabelCliente, gridBagConstraints);

        jLabelRuaNumero.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelRuaNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRuaNumero.setText("Rua Teste, 123");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        add(jLabelRuaNumero, gridBagConstraints);

        jLabelBairro.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelBairro.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBairro.setText("Vila Teste");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(jLabelBairro, gridBagConstraints);

        jLabelCidadeUF.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelCidadeUF.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCidadeUF.setText("Nova Europa - SP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 80, 0);
        add(jLabelCidadeUF, gridBagConstraints);

        jButtonNão.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNão.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonNão.setForeground(new java.awt.Color(28, 88, 199));
        jButtonNão.setText("NÃO");
        jButtonNão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNãoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 50;
        add(jButtonNão, gridBagConstraints);

        jButtonSim.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSim.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSim.setForeground(new java.awt.Color(28, 88, 199));
        jButtonSim.setText("SIM");
        jButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 70;
        gridBagConstraints.ipady = 50;
        add(jButtonSim, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        this.baseJFrame.mudarTela(Const.TELA_CPF);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimActionPerformed

        this.baseJFrame.getAutomacaoCTR().setConfirmarCliente(true);
        mudarTela();

    }//GEN-LAST:event_jButtonSimActionPerformed

    private void jButtonNãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNãoActionPerformed

        this.baseJFrame.getAutomacaoCTR().setConfirmarCliente(false);
        this.baseJFrame.mudarTela(Const.TELA_LISTA_CLIENTE);

    }//GEN-LAST:event_jButtonNãoActionPerformed

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed

        this.baseJFrame.retornarTela();

    }//GEN-LAST:event_jButtonRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonNão;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JButton jButtonSim;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCidadeUF;
    private javax.swing.JLabel jLabelCliente;
    private javax.swing.JLabel jLabelPerg;
    private javax.swing.JLabel jLabelRuaNumero;
    // End of variables declaration//GEN-END:variables

    private void mudarTela() {
        if (this.baseJFrame.getAutomacaoCTR().isMotoristaExistente()) {
            this.baseJFrame.mudarTela(Const.TELA_ULT_TRANSP_CARREG);
        } else {
            this.baseJFrame.mudarTela(Const.TELA_PLACA);
        }
    }

    private void carreg() {
        jLabelCliente.setText(this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getDescrCliente());
        jLabelRuaNumero.setText(this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getRuaCliente() + ", " + this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getNumCliente());
        jLabelBairro.setText(this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getBairroCliente() + " - " + this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getComplCliente());
        jLabelCidadeUF.setText(this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getCidadeCliente() + " - " + this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getEstadoCliente());
    }

    @Override
    public Dimension getPreferredSize() {
        Dimension superSize = super.getPreferredSize();
        if (isPreferredSizeSet() || image == null) {
            return superSize;
        }
        int prefW = Math.max(image.getWidth(null), superSize.width);
        int prefH = Math.max(image.getHeight(null), superSize.height);
        return new Dimension(prefW, prefH);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, null);
        }
    }

}
