/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import util.Const;

/**
 *
 * @author anderson
 */
public class TelaReimprimirJPanel extends javax.swing.JPanel {

    private final Image image;
    private final BaseJFrame baseJFrame;
    private final DefaultJDialog defaultJDialog;
    
    /**
     * Creates new form TelaCamCPreOrdemJPanel
     */
    public TelaReimprimirJPanel(BaseJFrame baseJFrame) {
        this.baseJFrame = baseJFrame;
        initComponents();
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/util/layout_totem.jpg"));
        this.image = imageIcon.getImage();
        preencher();
        defaultJDialog = new DefaultJDialog(new javax.swing.JFrame(), true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonCancelar = new javax.swing.JButton();
        jButtonRetornar = new javax.swing.JButton();
        jButtonReimpressao = new javax.swing.JButton();
        jButtonOK = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabelMsg = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        add(jButtonCancelar, gridBagConstraints);

        jButtonRetornar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRetornar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRetornar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonRetornar.setText("RETORNAR");
        jButtonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        add(jButtonRetornar, gridBagConstraints);

        jButtonReimpressao.setBackground(new java.awt.Color(255, 255, 255));
        jButtonReimpressao.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonReimpressao.setForeground(new java.awt.Color(28, 88, 199));
        jButtonReimpressao.setText("REIMPRESSÃO");
        jButtonReimpressao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReimpressaoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 10);
        add(jButtonReimpressao, gridBagConstraints);

        jButtonOK.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOK.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonOK.setForeground(new java.awt.Color(28, 88, 199));
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 60;
        gridBagConstraints.ipady = 50;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 30);
        add(jButtonOK, gridBagConstraints);

        jScrollPane2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N

        jLabelMsg.setColumns(20);
        jLabelMsg.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMsg.setRows(1);
        jScrollPane2.setViewportView(jLabelMsg);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 280;
        gridBagConstraints.ipady = 250;
        gridBagConstraints.insets = new java.awt.Insets(80, 0, 80, 0);
        add(jScrollPane2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
        this.baseJFrame.mudarTela(Const.TELA_CPF);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed

        this.baseJFrame.retornarTela();
        
    }//GEN-LAST:event_jButtonRetornarActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        
        this.baseJFrame.mudarTela(Const.TELA_CPF);
        
    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonReimpressaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReimpressaoActionPerformed
        
        reimprimir();
        
    }//GEN-LAST:event_jButtonReimpressaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonReimpressao;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JTextArea jLabelMsg;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    private void reimprimir(){
        switch (this.baseJFrame.getAutomacaoCTR().reimprimir()) {
            case "Retorno":
                this.baseJFrame.mudarTela(Const.TELA_CPF);
                break;
            case "MSG":
                msg();
                break;
            case "NãoContemPreOrdem":
                naoContemPreOrdem();
                break;
        }
    }
    
    public void preencher() {
        jLabelMsg.setText(this.baseJFrame.getAutomacaoCTR().getUltViagemBean().getMsgErro().replace(".", ".\n").toUpperCase());
        jLabelMsg.setLineWrap(true);
    }
    
    public void msg() {
        defaultJDialog.setTxtMsg(this.baseJFrame.getAutomacaoCTR().getMsg());
        Timer timer = new Timer(4000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                defaultJDialog.setVisible(false);
            }
        });
        timer.setRepeats(false);
        timer.start();
        defaultJDialog.setVisible(true);
    }

    public void naoContemPreOrdem() {
        defaultJDialog.setTxtMsg("NÃO CONTÉM NENHUMA PRÉ ORDEM DE CARREGAMENTO PARA ESSE CPF! POR FAVOR, ENTRE EM CONTATO COM O NÚCLEO FISCAL.");
        Timer timer = new Timer(4000, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                defaultJDialog.setVisible(false);
            }
        });
        timer.setRepeats(false);
        timer.start();
        defaultJDialog.setVisible(true);
    }

    @Override
    public Dimension getPreferredSize() {
        Dimension superSize = super.getPreferredSize();
        if (isPreferredSizeSet() || image == null) {
            return superSize;
        }
        int prefW = Math.max(image.getWidth(null), superSize.width);
        int prefH = Math.max(image.getHeight(null), superSize.height);
        return new Dimension(prefW, prefH);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, null);
        }
    }

}
