/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import util.Const;

/**
 *
 * @author anderson
 */
public class TelaImprimirSenhaJPanel extends javax.swing.JPanel {

    private final Image image;
    private final BaseJFrame baseJFrame;
    private boolean fechaTela;

    /**
     * Creates new form TelaImprimirSenhaJPanel
     */
    public TelaImprimirSenhaJPanel(BaseJFrame baseJFrame) {
        this.baseJFrame = baseJFrame;
        initComponents();
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/util/layout_totem.jpg"));
        this.image = imageIcon.getImage();
        fechaTela = false;
        exibir();
        timerFecharTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonCancelar = new javax.swing.JButton();
        jButtonRetornar = new javax.swing.JButton();
        jLabelMsgInicial = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jScroll = new javax.swing.JScrollPane();
        jLabelMsg = new javax.swing.JTextArea();
        jButtonOK = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        add(jButtonCancelar, gridBagConstraints);

        jButtonRetornar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRetornar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRetornar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonRetornar.setText("RETORNAR");
        jButtonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        add(jButtonRetornar, gridBagConstraints);

        jLabelMsgInicial.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelMsgInicial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMsgInicial.setText("Ok, registro efetuado com sucesso, retire sua senha:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 0, 0);
        add(jLabelMsgInicial, gridBagConstraints);

        jLabelSenha.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabelSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSenha.setText("00000ASC");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        add(jLabelSenha, gridBagConstraints);

        jLabelStatus.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 51, 0));
        jLabelStatus.setText("Status: Pendende de liberação transportadora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        add(jLabelStatus, gridBagConstraints);

        jLabelMsg.setColumns(20);
        jLabelMsg.setFont(new java.awt.Font("Tahoma", 0, 28)); // NOI18N
        jLabelMsg.setRows(5);
        jScroll.setViewportView(jLabelMsg);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        add(jScroll, gridBagConstraints);

        jButtonOK.setBackground(new java.awt.Color(255, 255, 255));
        jButtonOK.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jButtonOK.setForeground(new java.awt.Color(28, 88, 199));
        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 40;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(jButtonOK, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        this.baseJFrame.mudarTela(Const.TELA_CPF);

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed

        fechaTela = true;
        this.baseJFrame.mudarTela(Const.TELA_CPF);

    }//GEN-LAST:event_jButtonOKActionPerformed

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed

        this.baseJFrame.mudarTela(Const.TELA_CPF);

    }//GEN-LAST:event_jButtonRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JTextArea jLabelMsg;
    private javax.swing.JLabel jLabelMsgInicial;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JScrollPane jScroll;
    // End of variables declaration//GEN-END:variables

    public void exibir() {
        
        jLabelSenha.setText(this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getSenha());
        jLabelStatus.setText("STATUS: " + this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().getDescrEtapa());
        jLabelMsg.setText(this.baseJFrame.getAutomacaoCTR().msgImprimir().replace(".", ".\n").toUpperCase());
        jLabelMsg.setLineWrap(true);

        this.baseJFrame.getAutomacaoCTR().imprimir();

    }

    private void timerFecharTela() {
        Timer t = new Timer(30000, (ActionEvent e) -> {
            fecharTela();
        });
        t.start();
    }

    private void fecharTela() {
        if (!fechaTela) {
            fechaTela = true;
            this.baseJFrame.mudarTela(Const.TELA_CPF);
        }
    }

    @Override
    public Dimension getPreferredSize() {
        Dimension superSize = super.getPreferredSize();
        if (isPreferredSizeSet() || image == null) {
            return superSize;
        }
        int prefW = Math.max(image.getWidth(null), superSize.width);
        int prefH = Math.max(image.getHeight(null), superSize.height);
        return new Dimension(prefW, prefH);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, null);
        }
    }

}
