/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package view;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import util.Const;

/**
 *
 * @author anderson
 */
public class TelaUltVeicCarregJPanel extends javax.swing.JPanel {

    private final Image image;
    private final BaseJFrame baseJFrame;
    
    /** Creates new form TelaVeicUltCarregJPanel */
    public TelaUltVeicCarregJPanel(BaseJFrame baseJFrame) {
        this.baseJFrame = baseJFrame;
        initComponents();
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/util/layout_totem.jpg"));
        this.image = imageIcon.getImage();
        carreg();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonCancelar = new javax.swing.JButton();
        jButtonRetornar = new javax.swing.JButton();
        jLabelVeicUltCarreg = new javax.swing.JLabel();
        jLabelVeiculo = new javax.swing.JLabel();
        jLabelPlaca1 = new javax.swing.JLabel();
        jLabelPlaca2 = new javax.swing.JLabel();
        jLabelPlaca3 = new javax.swing.JLabel();
        jLabelCapacidade = new javax.swing.JLabel();
        jButtonNão = new javax.swing.JButton();
        jButtonSim = new javax.swing.JButton();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        add(jButtonCancelar, gridBagConstraints);

        jButtonRetornar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRetornar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRetornar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonRetornar.setText("RETORNAR");
        jButtonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 50;
        add(jButtonRetornar, gridBagConstraints);

        jLabelVeicUltCarreg.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelVeicUltCarreg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVeicUltCarreg.setText("Veículo a ser carregado contém?");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 10, 0);
        add(jLabelVeicUltCarreg, gridBagConstraints);

        jLabelVeiculo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVeiculo.setText("VEÍCULO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 10, 0);
        add(jLabelVeiculo, gridBagConstraints);

        jLabelPlaca1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPlaca1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlaca1.setText("Placa 1: AAA-0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(jLabelPlaca1, gridBagConstraints);

        jLabelPlaca2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPlaca2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlaca2.setText("Placa 1: AAA-0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(jLabelPlaca2, gridBagConstraints);

        jLabelPlaca3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelPlaca3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlaca3.setText("Placa 1: AAA-0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 5, 0);
        add(jLabelPlaca3, gridBagConstraints);

        jLabelCapacidade.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabelCapacidade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCapacidade.setText("Capacidade: 650 SCS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 40, 0);
        add(jLabelCapacidade, gridBagConstraints);

        jButtonNão.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNão.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonNão.setForeground(new java.awt.Color(28, 88, 199));
        jButtonNão.setText("NÃO");
        jButtonNão.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNãoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(0, 100, 0, 10);
        add(jButtonNão, gridBagConstraints);

        jButtonSim.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSim.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonSim.setForeground(new java.awt.Color(28, 88, 199));
        jButtonSim.setText("SIM");
        jButtonSim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSimActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 80;
        gridBagConstraints.ipady = 60;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 100);
        add(jButtonSim, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        
        this.baseJFrame.mudarTela(Const.TELA_CPF);
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonNãoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNãoActionPerformed
        
        this.baseJFrame.getAutomacaoCTR().setConfirmarVeic(false);
        this.baseJFrame.mudarTela(Const.TELA_PLACA);
        
    }//GEN-LAST:event_jButtonNãoActionPerformed

    private void jButtonSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSimActionPerformed
        
        this.baseJFrame.getAutomacaoCTR().setConfirmarVeic(true);
        this.baseJFrame.mudarTela(Const.TELA_CAMERA);

    }//GEN-LAST:event_jButtonSimActionPerformed

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed

        this.baseJFrame.retornarTela();
                
    }//GEN-LAST:event_jButtonRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonNão;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JButton jButtonSim;
    private javax.swing.JLabel jLabelCapacidade;
    private javax.swing.JLabel jLabelPlaca1;
    private javax.swing.JLabel jLabelPlaca2;
    private javax.swing.JLabel jLabelPlaca3;
    private javax.swing.JLabel jLabelVeicUltCarreg;
    private javax.swing.JLabel jLabelVeiculo;
    // End of variables declaration//GEN-END:variables
    
    private void carreg() {
        jLabelPlaca1.setText("Placa 1: " + this.baseJFrame.getAutomacaoCTR().getUltViagemBean().getPlaca1());
        jLabelPlaca2.setText("Placa 2: " + this.baseJFrame.getAutomacaoCTR().getUltViagemBean().getPlaca2());
        jLabelPlaca3.setText("Placa 3: " + this.baseJFrame.getAutomacaoCTR().getUltViagemBean().getPlaca3());
        jLabelCapacidade.setText("Capacidade: " + this.baseJFrame.getAutomacaoCTR().getUltViagemBean().getCapacidade());
    }

    @Override
    public Dimension getPreferredSize() {
        Dimension superSize = super.getPreferredSize();
        if (isPreferredSizeSet() || image == null) {
            return superSize;
        }
        int prefW = Math.max(image.getWidth(null), superSize.width);
        int prefH = Math.max(image.getHeight(null), superSize.height);
        return new Dimension(prefW, prefH);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, null);
        }
    }

}
