/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author anderson
 */
public class TelaPlacaJPanel extends javax.swing.JPanel {

    private final Image image;
    private final BaseJFrame baseJFrame;
    private final DefaultJDialog defaultJDialog;

    /**
     * Creates new form TelaPlacaJPanel
     */
    public TelaPlacaJPanel(BaseJFrame baseJFrame) {
        this.baseJFrame = baseJFrame;
        initComponents();
        ImageIcon imageIcon = new ImageIcon(getClass().getResource("/util/layout_totem.jpg"));
        this.image = imageIcon.getImage();
        defaultJDialog = new DefaultJDialog(new javax.swing.JFrame(), true);
        jLabelPlaca.setText("___-____");
        this.baseJFrame.getAutomacaoCTR().setQtde(0);
        this.baseJFrame.getAutomacaoCTR().setTextoPlaca("");
        this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().setPlaca1("");
        this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().setPlaca2(null);
        this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().setPlaca3(null);
        chamaTecladoLetra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButtonCancelar = new javax.swing.JButton();
        jButtonRetornar = new javax.swing.JButton();
        jLabelMsg = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jPanelPrincPlaca = new javax.swing.JPanel();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        jButtonCancelar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 70;
        add(jButtonCancelar, gridBagConstraints);

        jButtonRetornar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRetornar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButtonRetornar.setForeground(new java.awt.Color(28, 88, 199));
        jButtonRetornar.setText("RETORNAR");
        jButtonRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRetornarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.ipady = 70;
        add(jButtonRetornar, gridBagConstraints);

        jLabelMsg.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMsg.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMsg.setText("Registre sua placa.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        add(jLabelMsg, gridBagConstraints);

        jLabelPlaca.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabelPlaca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPlaca.setText("___-____");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 20, 0);
        add(jLabelPlaca, gridBagConstraints);

        jPanelPrincPlaca.setOpaque(false);

        javax.swing.GroupLayout jPanelPrincPlacaLayout = new javax.swing.GroupLayout(jPanelPrincPlaca);
        jPanelPrincPlaca.setLayout(jPanelPrincPlacaLayout);
        jPanelPrincPlacaLayout.setHorizontalGroup(
            jPanelPrincPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelPrincPlacaLayout.setVerticalGroup(
            jPanelPrincPlacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 800;
        gridBagConstraints.ipady = 450;
        add(jPanelPrincPlaca, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed

        this.baseJFrame.mudarTela("TelaCPFJPanel");

    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRetornarActionPerformed

        this.baseJFrame.retornarTela();

    }//GEN-LAST:event_jButtonRetornarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonRetornar;
    private javax.swing.JLabel jLabelMsg;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JPanel jPanelPrincPlaca;
    // End of variables declaration//GEN-END:variables

    public void preencherPlaca(String letraNumPlaca) {
        switch (this.baseJFrame.getAutomacaoCTR().getQtde()) {
            case 2:
                chamaTecladoNum();
                break;
            case 3:
                chamaTecladoLetraNum();
                break;
            case 4:
                chamaTecladoNum();
                break;
            default:
                break;
        }
        jLabelPlaca.setText(this.baseJFrame.getAutomacaoCTR().preencherPlaca(letraNumPlaca));
    }

    public void apagarPlaca() {
        switch (this.baseJFrame.getAutomacaoCTR().getQtde()) {
            case 3:
                chamaTecladoLetra();
                break;
            case 4:
                chamaTecladoNum();
                break;
            case 5:
                chamaTecladoLetraNum();
                break;
            case 6:
                chamaTecladoNum();
                break;
            default:
                break;
        }
        jLabelPlaca.setText(this.baseJFrame.getAutomacaoCTR().apagarPlaca());
    }

    public void ok() {

        if (this.baseJFrame.getAutomacaoCTR().getQtde() == 7) {

            this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().setPlaca1(this.baseJFrame.getAutomacaoCTR().getTextoPlaca());
            this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().setPlaca2("");
            this.baseJFrame.getAutomacaoCTR().getDadosCarregBean().setPlaca3("");
            this.baseJFrame.mudarTela("TelaCameraJPanel");

        } else {

            terminarPlaca();

        }
    }

    public void terminarPlaca() {
        defaultJDialog.setTxtMsg("Por Favor, termine de digitar a placa do Veículo.");
        Timer timer = new Timer(4000, (ActionEvent e) -> {
            defaultJDialog.setVisible(false);
        });
        timer.setRepeats(false);
        timer.start();
        defaultJDialog.setVisible(true);
    }

    private void chamaTecladoLetra() {

        TecladoLetraJPanel jPanelTecladoLetra = new TecladoLetraJPanel(this);
        jPanelTecladoLetra.setSize(820, 285);
        jPanelTecladoLetra.setLocation(0, 0);

        jPanelPrincPlaca.removeAll();
        jPanelPrincPlaca.add(jPanelTecladoLetra, BorderLayout.CENTER);
        jPanelPrincPlaca.revalidate();
        jPanelPrincPlaca.repaint();

    }

    public void chamaTecladoNum() {

        TecladoNumJPanel jPanelTecladoNum = new TecladoNumJPanel(this);
        jPanelTecladoNum.setSize(820, 440);
        jPanelTecladoNum.setLocation(0, 0);

        jPanelPrincPlaca.removeAll();
        jPanelPrincPlaca.add(jPanelTecladoNum, BorderLayout.CENTER);
        jPanelPrincPlaca.revalidate();
        jPanelPrincPlaca.repaint();

    }

    public void chamaTecladoLetraNum() {

        TecladoNumLetraJPanel jPanelTecladoNumLetra = new TecladoNumLetraJPanel(this);
        jPanelTecladoNumLetra.setSize(820, 440);
        jPanelTecladoNumLetra.setLocation(0, 0);

        jPanelPrincPlaca.removeAll();
        jPanelPrincPlaca.add(jPanelTecladoNumLetra, BorderLayout.CENTER);
        jPanelPrincPlaca.revalidate();
        jPanelPrincPlaca.repaint();

    }

    @Override
    public Dimension getPreferredSize() {
        Dimension superSize = super.getPreferredSize();
        if (isPreferredSizeSet() || image == null) {
            return superSize;
        }
        int prefW = Math.max(image.getWidth(null), superSize.width);
        int prefH = Math.max(image.getHeight(null), superSize.height);
        return new Dimension(prefW, prefH);
    }

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        if (image != null) {
            g.drawImage(image, 0, 0, null);
        }
    }

}
